### ISSUE TITLE
Doesn't detect some Blackberry 10 UAs

### ISSUE THREAD

**Issue by triblondon** [ua-parser/uap-core#102]
Known Blackberry 10 UA:

```
Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35  (KHTML, like Gecko) Version/10.3.1.2243 Mobile Safari/537.35
```

This comes out as BlackBerry Webkit 0.0.0.  Tested with npm useragent module having run its internal update process to bring in the master copy of the regexes from here.

```
Agent {
  family: 'BlackBerry WebKit',
  major: '0',
  minor: '0',
  patch: '0',
  source: 'Mozilla/5.0 (BB10; Touch) AppleWebKit/537.35  (KHTML, like Gecko) Version/10.3.1.2243 Mobile Safari/537.35' }
```

This UA string matches the pattern explained by BB in [this blog post](http://devblog.blackberry.com/2012/08/blackberry-10-user-agent-string/).  Issue in the polyfill service: https://github.com/Financial-Times/polyfill-service/issues/491.

**Comment by commenthol** [comment]
Thanks
