### ISSUE TITLE
SMART-TV, Tizen, SamsungBrowser

### ISSUE THREAD

**Issue by waldbaerkoch** [ua-parser/uap-core#113]
User-Agent: Mozilla/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1

```
{
    "ua": {
        "major": null,
        "minor": null,
        "patch": null,
        "family": "Safari"
    },
    "os": {
        "major": null,
        "minor": null,
        "patch": null,
        "patchMinor": null,
        "family": "Linux"
    },
    "device": {
        "brand": null,
        "model": null,
        "family": "Other"
    },
    "originalUserAgent": "Mozilla\/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit\/538.1 (KHTML, like Gecko) SamsungBrowser\/1.0 TV Safari\/538.1"
}
```
1. No device is recognized
2. OS is not recognized as Tizen 2.3.
   The regex in regexes.yaml is

```
  ##########
  # Tizen OS from Samsung
  # spoofs Android so pushing it above
  ##########
  - regex: '(Tizen)/(\d+)\.(\d+)'
```

But according to http://developer.samsung.com/technical-doc/view.do?v=T000000203 there should be no `/` between platform and platform version:
Mozilla/$(MOZILA_VER) ($(DEVICE_TYPE); $(OS); $(PLATFORM) $(PLATFORM_VER);
SAMSUNG $(MODEL_NAME) Build/$(BUILD_TAG)) AppleWebKit/$(APPLEWEBKIT_VER)
(KHTML, like Gecko) $(APP_NAME)/$(APP_VER) (Chrome/$(CHROME_VER))
$(UX RECOMMEND) Safari/$(SAFARI_VER)
3. The browser is recognized as Safari which looks like a fallback for comething more specific.

**Comment by commenthol** [comment]
Device recognition is still open. Could be `{family: ''Smart TV", brand: "Samsung", model: "Smart TV"}` ...

**Comment by waldbaerkoch** [comment]
commenthol: OK
