### ISSUE TITLE
Issues matching device

### ISSUE THREAD

**Issue by VassilAtanasov** [ua-parser/uap-core#118]
Hi Guys, 
How can I have devices parsed into more generic family like (Desktop, Tablet, Phone, TV)?
Current parsing results aim to identify exact device model but not the type.

Also I've noticed some parse issues resulting to like $1$2 or $1$2$3$4. 
Examples:
![image](https://cloud.githubusercontent.com/assets/13772248/11424399/c61b3c5e-9444-11e5-918a-42d26bb47c96.png)

Mozilla/5.0 (Linux; Android 4.4.4; Y635-L21 Build/HuaweiY635-L21) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.4; Y635-L21 Build/HuaweiY635-L21) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.4.2; U25GT-C4W Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36
Mozilla/5.0 (Linux; Android 4.2.2; U55GT Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36
Mozilla/5.0 (Linux; Android 4.2.2; U55GT Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Safari/537.36
Mozilla/5.0 (Linux; Android 4.2.2; ZP980  Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.2.2; ZP980  Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
Mozilla/5.0 (Linux; Android 4.2.2; ZP980  Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.76 Mobile Safari/537.36
Mozilla/5.0 (Linux; U; Android 4.2.1; ca-es; ZP980 Build/JOP40D) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-US; Mi-440 Build/KOT49H) AppleWebKit/528.5  (KHTML, like Gecko) Version/3.1.2 Mobile Safari/525.20.1 UCBrowser/9.4.0.460 Mobile
Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 8675 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 baiduboxapp/5.0 (Baidu; P1 4.4.2)
Mozilla/5.0 (Linux; U; Android 4.4.4; zh-CN; Coolpad 8297-T01 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.5.689 U3/0.8.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.4; zh-CN; Coolpad 8297-T01 Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.5.689 U3/0.8.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; Android 4.4.4; Coolpad 8297-C00 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 SogouSearch Android1.0 version3.0
Mozilla/5.0 (Linux; Android 4.4.4; Coolpad 8675-FHD Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 Mb2345Browser/7.5.1
Mozilla/5.0 (Linux; U; Android 4.3; zh-CN; Coolpad 8730L Build/JLS36C) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.5.689 U3/0.8.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.0.3; zh-CN; Coolpad 8089 Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.5.689 U3/0.8.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.0.3; zh-CN; Coolpad 8089 Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/10.8.5.689 U3/0.8.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; zh-cn; Coolpad 8675 Build/KOT49H) AppleWebKit/534.24 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.24 T5/2.0 baiduboxapp/6.9.6 (Baidu; P1 4.4.2)
Mozilla/5.0 (Linux; Android 4.4.2; Coolpad 7620L-W00 Build/KVT49L) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/54.0.0.0.25;]
Mozilla/5.0 (Linux; U; Android 4.2.2; en-us; GFIVE A5 Build/JDQ39) AppleWebKit/534.24 (KHTML, like Gecko) FlyFlow/3.1 Version/4.0 Mobile Safari/534.24 T5/2.0
Mozilla/5.0 (Linux; Android 4.4.2; HTC 802t 16GB Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Mobile Safari/537.36 wkbrowser 3.2.56 696
Mozilla/5.0 (Linux; Android 4.4.4; HTC Desire 820 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 ACHEETAHI/2100502012

**Comment by commenthol** [comment]
The experienced issue seams to be related to the parser you are using.
Please open an issue at the related parser project.

Below the parsing result of the nodejs parser.
```
Huawei      Y635-L21    Y635-L21    Mozilla/5.0 (Linux; Android 4.4.4; Y635
Huawei      Y635-L21    Y635-L21    Mozilla/5.0 (Linux; Android 4.4.4; Y635
Cube        U25GT-C4W   U25GT-C4W   Mozilla/5.0 (Linux; Android 4.4.2; U25G
Cube        U55GT       U55GT       Mozilla/5.0 (Linux; Android 4.2.2; U55G
Cube        U55GT       U55GT       Mozilla/5.0 (Linux; Android 4.2.2; U55G
Zopo        ZP980       ZP980       Mozilla/5.0 (Linux; Android 4.2.2; ZP98
Zopo        ZP980       ZP980       Mozilla/5.0 (Linux; Android 4.2.2; ZP98
Zopo        ZP980       ZP980       Mozilla/5.0 (Linux; Android 4.2.2; ZP98
Zopo        ZP980       ZP980       Mozilla/5.0 (Linux; U; Android 4.2.1; c
Spice       Mi440       Mi-440      Mozilla/5.0 (Linux; U; Android 4.4.2; e
Coolpad     8675        8675        Mozilla/5.0 (Linux; Android 4.4.2; Cool
Coolpad     8297-T01    8297-T01    Mozilla/5.0 (Linux; U; Android 4.4.4; z
Coolpad     8297-T01    8297-T01    Mozilla/5.0 (Linux; U; Android 4.4.4; z
Coolpad     8297-C00    8297-C00    Mozilla/5.0 (Linux; Android 4.4.4; Cool
Coolpad     8675-FHD    8675-FHD    Mozilla/5.0 (Linux; Android 4.4.4; Cool
Coolpad     8730L       8730L       Mozilla/5.0 (Linux; U; Android 4.3; zh-
Coolpad     8089        8089        Mozilla/5.0 (Linux; U; Android 4.0.3; z
Coolpad     8089        8089        Mozilla/5.0 (Linux; U; Android 4.0.3; z
Coolpad     8675        8675        Mozilla/5.0 (Linux; U; Android 4.4.2; z
Coolpad     7620L-W00   7620L-W00   Mozilla/5.0 (Linux; Android 4.4.2; Cool
Gfive       A5          GFIVE A5    Mozilla/5.0 (Linux; U; Android 4.2.2; e
HTC         802t 16GB   HTC 802t 16GB           Mozilla/5.0 (Linux; Android
HTC         Desire 820  HTC Desire 820          Mozilla/5.0 (Linux; Android
```
