### ISSUE TITLE
uap-lua

### ISSUE THREAD

**Issue by tpimh** [ua-parser/uap-core#124]
Lua is pretty popular nowadays.
I guess it is not yet supported because it has certain problems with regexps.
Is anyone working on uap-lua?

**Comment by russellwhitaker** [comment]
Apparently not. You want to take a crack at it @tpimh ?

**Comment by dukex** [comment]
@russellwhitaker and @tpimh I started to working on it, please take a look https://github.com/megafono/uap-lua
