### ISSUE TITLE
Playstation 3|4 and other console detection

### ISSUE THREAD

**Issue by Shinkurt** [ua-parser/uap-core#141]
Hi,

This great project detects Playstation cosoles as "other". I am requesting this to be included in next version.
PS3,PS4,Xbox One, PSP... 

Thanks

**Comment by russellwhitaker** [comment]
Suggest you generate a candidate regex in regexes.yaml along with confirmatory tests in the various test fixtures, and generate a pull request, if you want this done.

**Comment by Shinkurt** [comment]
@russellwhitaker I use the php version and I couldn't find that file you were referencing

**Comment by tobie** [comment]
That file is here: https://github.com/ua-parser/uap-core/blob/master/regexes.yaml

It's shared across languages.

**Comment by russellwhitaker** [comment]
@Shinkurt were you planning on submitting a candidate regex with confirming tests?

**Comment by Shinkurt** [comment]
@russellwhitaker not really. been busy

**Comment by russellwhitaker** [comment]
@Shinkurt you're exceedingly unlikely to get any one of the other busy folk here to do your requested work. If you submit candidate code yourself though, it'll get looked at and reviewed, maybe merged. Because opensource.

**Comment by Shinkurt** [comment]
@russellwhitaker sure. its just not an urgent matter, I will push a fork when I can.
