### ISSUE TITLE
LG Nexus 5X, Huawei Nexus 6P

### ISSUE THREAD

**Issue by waldbaerkoch** [ua-parser/uap-core#142]
LG Nexus 5X:
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.96 Mobile Safari/537.36

Huawei Nexus 6P:
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6P Build/MHC19Q) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.89 Mobile Safari/537.36

both match as brand: 'Generic_Android'
The brand for Nexus 5X should be 'LG'.
The brand for Nexus 6P should be 'Huawei'.

In the LG section, there is already a regex matching 'Nexus 4' and 'Nexus 5'.

**Comment by commenthol** [comment]
Merged
