### ISSUE TITLE
Not recognize device for a couple of tests

### ISSUE THREAD

**Issue by mmarmol** [ua-parser/uap-core#151]
This is my chrome on a windows 10 dell laptop
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
This one is same windows 10 dell laptop for edge
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

They are not recognized as desktop or laptop, just others. 

I see that some others libs understand that is a desktop and some not, here is one it does:
https://useragentapi.com/

I was wondering, what part of this useragent string may indicate desktop? The WOW64? or the Win46?
No clue really, maybe when they just dont know what to say they say desktop instead of others.

**Comment by ThaDafinser** [comment]
The "default" is currently mostly desktop. There are normally indicators that it's not a desktop browser.

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F46.0.2486.0+Safari%2F537.36+Edge%2F13.10586

**Comment by mmarmol** [comment]
@ThaDafinser  So at least on the java lib for ua-parser the code indicates to fallback to "Others" 
		for (DevicePattern p : patterns) {
			if ((device = p.match(agentString)) != null) {
				cache.putDevice(agentString, device);
				return device;
			}
		}
		device = new Device("Other", null, null);
It would be more reasonable to fallback to "Desktop" ?

**Comment by ThaDafinser** [comment]
You missunderstood me :-)

Default to Other like now is fine. But if you have a UA, which gets detected in most cases it will be desktop, because there is no direct indicator for "desktop"

**Comment by mmarmol** [comment]
@ThaDafinser My read from your comments is that most UA parser when they dont know what to say they fallback to Desktop. That make sense? If so it may be more readable to do the same as a resulting output than Other. What you think?
