### ISSUE TITLE
Type for devices?

### ISSUE THREAD

**Issue by mmarmol** [ua-parser/uap-core#152]
This is a feature request.

Right now Device return this 3 fields:
device_replacement:     
brand_replacement: 
model_replacement:

It would be helpful if we add a consolidating type on device, something like device_type that will have as possible values Desktop, SmartWatch, Phone, Tablet etc. A single field with only a few enumerated values would be easy to read and to make code based on it, right now there is to much information that it would need an independent regex/marcher just to understand if the result is a Phone or a Tablet.

What you guys think?

**Comment by mimmi20** [comment]
please look uinto issue#31.

**Comment by mmarmol** [comment]
Got it, I will close it.
