### ISSUE TITLE
Performance improvement when placing most common browser/os/device on top of the regexes list

### ISSUE THREAD

**Issue by vahemark** [ua-parser/uap-core#153]
There would be noticeably faster parsing when the browsers and operating systems which have the most market share are placed on top of the regexes list. Due to looping through the list, the more chances we have a match the sooner we break the loop and return the result, and the less we utilize the CPU.

Perhaps, there are few use cases when performance is important such as aggregation and statistics generation purposes when one needs to parse a huge list of user agents.

**Comment by russellwhitaker** [comment]
@vahemark do you have a version of regexes.yaml with which you've tested this supposition?

**Comment by commenthol** [comment]
IMHO this might be difficult due to interdependencies in the regexes file. Means some "not so common now" user-agents need to come before the "now common" ones, which then again changes in 6 months.
As user-agents for a certain time tends to be quite unique, my recommendation is to use some caching mechanism.

**Comment by shashank-** [comment]
@vahemark we parse 200K+ UA unique strings on a weekly basis, and have found that we can typically cache the result the of single parse. A LRU dictionary (capped at an acceptable limit, we use 10K). Most of the traffic comes from just a some common sources.

@commenthol I agree, we have noticed that Facebook this year has become a large source of traffic, and they create UA strings with a lot of variation.
