### ISSUE TITLE
Using Chrome on mac os comes out as 'Other'

### ISSUE THREAD

**Issue by forceedge01** [ua-parser/uap-core#154]
We've just found out this issue. At the moment if you use Chrome on mac os x the device recorded by the ua-parser comes out as Other with no branch or model.

This is happening on v3.4.5.

**Comment by russellwhitaker** [comment]
@forceedge01 do you have the corresponding user agent string emitted by that instance of the browser?

**Comment by flansch** [comment]
It's the same for me:
```
Mozilla/5.0+(Macintosh;+Intel+Mac+OS+X+10_11_6)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/52.0.2743.116+Safari/537.36
```
results in _Device.Family_, _OS.Family_ and _UserAgent.Family_ all having the value _Other_.

**Comment by meal** [comment]
I've observed the same behaviour
