### ISSUE TITLE
LG Smart TVs

### ISSUE THREAD

**Issue by sbradysonifi** [ua-parser/uap-core#156]
I am working on an LG Set Top Box running webos and it is coming up as Safari. Here is the string

User Agent
Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.41 (KHTML, like Gecko) Large Screen WebAppManager Safari/537.41

It should probably be LG WebOS or webOS Browser. 

Thanks!

**Comment by russellwhitaker** [comment]
@sbradysonifi you should feel free to submit a pull request with a modified regexes.yaml and corresponding test coverage.
