### ISSUE TITLE
windows 7 IE 11 device type reports as tablet sometimes.

### ISSUE THREAD

**Issue by dwspeight** [ua-parser/uap-core#160]

**Comment by russellwhitaker** [comment]
@dwspeight do you have example useragent strings and associated output to share?

**Comment by dwspeight** [comment]
sorry but I don't.  It is happening for an external customer. I can't recreate it locally.  I was just hoping that you guys may already be aware of a problem.

**Comment by russellwhitaker** [comment]
When you researched the other 33 open issues before posting this one, did you find one like this?

**Comment by dwspeight** [comment]
I did research them but didn't see anything.  Below is what we captured

Technical_Info	2	OS_VERSION	7
To select row, press SPACEBAR	1034	SE3WOCZXSSET9H5FK1UTVGF_PGIE_SAP	1	Generic Inv Report	2016-07-27T12:09:34	Technical_Info	3	BROWSER_NAME	IE
To select row, press SPACEBAR	1035	SE3WOCZXSSET9H5FK1UTVGF_PGIE_SAP	1	Generic Inv Report	2016-07-27T12:09:34	Technical_Info	4	DEVICE_TYPE	tablet
To select row, press SPACEBAR	1036	SE3WOCZXSSET9H5FK1UTVGF_PGIE_SAP	1	Generic Inv Report	2016-07-27T12:09:34	Technical_Info	5	DOCUMENT_MODE	11
To select row, press SPACEBAR	1037	SE3WOCZXSSET9H5FK1UTVGF_PGIE_SAP	1	Generic Inv Report	2016-07-27T12:09:34	Technical_Info	6	DATE_AND_TIMESTAMP	Wed Jul 27 12:09:34 CDT 2016

**Comment by russellwhitaker** [comment]
If you didn't see anything in your research, then you have your answer, this being an opensource repo relying on contributions from motivated programmers such as yourself.

OK, as for that capture, what is that text, exactly? You'll need to provide useragent strings, associated output, and an indication of which implementation of the parser you and/or your customer is using. 

Have you taken a look yourself at the regexes.yaml file?

**Comment by dwspeight** [comment]
we have trapped the user-agent string that is causing uaparser to send device-type as tablet

Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko

When we run this string through the uaparser web tool it brings back device type of null but it seems the uaparser logic is sending device type of tablet

**Comment by commenthol** [comment]
There is something strange with your ua-parser version. Since years we do not provide any information on device-type like mobile, tablet, aso. There is only `family`, `brand` and `model` provided as info. I assume you are not using the latest regexes.yaml version from this project.
