### ISSUE TITLE
Samsung Internet share is confusingly high

### ISSUE THREAD

**Issue by dpp-name** [ua-parser/uap-core#162]
In PR #123 Samsung Internet was added, which classifies a lot of Chrome browsers (including pretty recent ones) as Samsung Internet. Why it is so important to have it as a separate name?

![samsungbrowser](https://cloud.githubusercontent.com/assets/387776/17852273/1073e112-686f-11e6-86ba-7bb65c6b0487.png)
We have to revert this PR for our use.

Examples:
Mozilla/5.0 (Linux; Android 4.4.4; en-au; SAMSUNG SM-N915G Build/KTU84P) AppleWebKit/537.36 (KTHML, like Gecko) Version/2.0 Chrome/34.0.1847.76 Mobile Safari/537.36
Chrome Mobile,34,0,1847

Mozilla/5.0 (Linux; Android 5.0.2; SAMSUNG SM-G925F Build/LRX22G) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/4.0 Chrome/44.0.2403.133 Mobile Safari/537.36
Samsung Internet,4,0

**Comment by demoneaux** [comment]
The Samsung Internet browser is not the same as Chrome; it is a modified version of Chromium by Samsung, which has a very large market share.
