### ISSUE TITLE
Operating System not detected for iPhone and iPad

### ISSUE THREAD

**Issue by flansch** [ua-parser/uap-core#165]
_OS.Family_ is _Other_ for the following user agents while I think it should be _iOS_ because _Device.Family_ is _iPhone_ or _iPad_:

```
Mozilla/5.0+(iPhone;+CPU+iPhone+OS+9_3_1+like+Mac+OS+X)+AppleWebKit/601.1.46+(KHTML,+like+Gecko)+Version/9.0+Mobile/13E238+Safari/601.1
Mozilla/5.0+(iPad;+CPU+OS+9_3_1+like+Mac+OS+X)+AppleWebKit/601.1.46+(KHTML,+like+Gecko)+Version/9.0+Mobile/13E238+Safari/601.1
```

**Comment by commenthol** [comment]
This is not an issue with the regexes itself but with sanitizing the string before sending to the parser. Therefore I recommend adding a PR for each parser implementation.

**Comment by commenthol** [comment]
I need to correct myself. If this "+" instead of " " thing is limited to iPad/iPhone devices only the regexes can be adapted for those.
