### ISSUE TITLE
Need guides on adding new User Agent

### ISSUE THREAD

**Issue by hendyanto** [ua-parser/uap-core#176]
Hello guys,
my app just got a user-agent that is not supported currently,

this is the sample
`Kurio/3.1.9 Build 66400(Android Kitkat 4.4.4; Phone)`

If I want to add this to the list, where should i put it?

**Comment by commenthol** [comment]
Hi @hendyanto, If "Kurio" refers to a device then add it under the *device_parser* section. If it refers to a browser then the *user_agent_parsers* section is the correct one. If the User-Agent refers both to a unique device as well as a unique Browser then both sections need an update. HTH.
