### ISSUE TITLE
Facebook User Agents iPad wrong device family.

### ISSUE THREAD

**Issue by shashank-** [ua-parser/uap-core#177]
The family and model is being returned as iPad4,1 rather than just iPad.

Mozilla/5.0 (iPad; CPU OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 [FBAN/FBIOS;FBAV/68.0.0.49.70;FBBV/41924288;FBRV/0;FBDV/iPad4,1;FBMD/iPad;FBSN/iOS;FBSV/10.0.2;FBSS/2;FBCR/;FBID/tablet;FBLC/en_US;FBOP/5]

{   'device': {   'brand': 'Apple', 'family': 'iPad4,1', 'model': 'iPad4,1'},
    'os': {   'family': 'iOS',
              'major': '10',
              'minor': '0',
              'patch': '2',
              'patch_minor': None},
    'user_agent': {   'family': 'Facebook',
                      'major': '68',
                      'minor': '0',
                      'patch': '0'}}

**Comment by ThaDafinser** [comment]
Confirmed - http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28iPad%3B+CPU+OS+10_0_2+like+Mac+OS+X%29+AppleWebKit%2F602.1.50+%28KHTML%2C+like+Gecko%29+Mobile%2F14A456+%5BFBAN%2FFBIOS%3BFBAV%2F68.0.0.49.70%3BFBBV%2F41924288%3BFBRV%2F0%3BFBDV%2FiPad4%2C1%3BFBMD%2FiPad%3BFBSN%2FiOS%3BFBSV%2F10.0.2%3BFBSS%2F2%3BFBCR%2F%3BFBID%2Ftablet%3BFBLC%2Fen_US%3BFBOP%2F5%5D

**Comment by commenthol** [comment]
Accepted, device family should evaluate to "iPad". But I disagree not using the correct model as provided which is "iPad4,1"
