### ISSUE TITLE
Thunderbird with Lightning detected as Lightning

### ISSUE THREAD

**Issue by tpetry** [ua-parser/uap-core#184]
Years ago Lightning was a single application and detecting it as a single application was sensefull. But for now quite a long time Lightning is installed as an addon to Thunderbird resulting in a user agent for example `Mozilla/5.0 (Windows NT 6.3; WOW64; rv:45.0) Gecko/20100101 Thunderbird/45.4.0 Lightning/4.7.4`.

I would propose changing the regexes.yaml order so any appearance of `Lightning` combined with `Thunderbird` will result in a detection for `Thunderbird`.

Any objections to this change? If not i will make an Pull Request - but such a change should be discussed before.

**Comment by commenthol** [comment]
No objections from my side.
