### ISSUE TITLE
SRWare Iron detected as Chrome

### ISSUE THREAD

**Issue by commenthol** [ua-parser/uap-core#186]
See https://github.com/ua-parser/uap-php/issues/35

Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2750.0 Iron Safari/537.36

There is no longer a slash and a version number after "Iron" in the string.

**Comment by waldbaerkoch** [comment]
In our logs I found these User-Agents indicating that the change was at least with version 49:

Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2600.0 Iron Safari/537.36
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2650.0 Iron Safari/537.36
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2700.0 Iron Safari/537.36
