### ISSUE TITLE
Two chrome-based browsers (baidubrowser, Dragon) not recognized as more specific browsers

### ISSUE THREAD

**Issue by waldbaerkoch** [ua-parser/uap-core#202]
baidubrowser:
```
Mozilla/5.0 (Linux; Android 5.1.1; MI NOTE Pro Build/LMY47V; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/48.0.2564.116 Mobile Safari/537.36 baidubrowser/7.7.13.0 (Baidu; P1 5.1.1)
```
is recognized as Chrome Mobile 48.0.2564, though there is a regex for `(baidubrowser)[/\s](\d+)`. Additionally, minor (and patch) version could be extracted.

Dragon:
```
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Dragon/36.1.1.21 Chrome/36.0.1985.97 Safari/537.36
```
is recognized as Chrome 36.0.1985.
There is a regex for `(Comodo_Dragon)/(\d+)\.(\d+)\.(\d+)`. In our logs, I could not find User-Agents header values containing 'Comodo_Dragon' (maybe this was used in some older versions). The 'Comodo_' part could be made optional.

**Comment by waldbaerkoch** [comment]
Now we have two browser families: 'Comodo Dragon' **and** 'Dragon'. I would prefer to map the regex 'Dragon' to the existing family 'Comodo Dragon' **or** to map 'Comodo_Dragon' to the new family 'Dragon'.

**Comment by commenthol** [comment]
Please find below a UA for "Comodo_Dragon"
```
Mozilla/5.0 (Windows; U; Windows NT 6.2; en-US) AppleWebKit/534.13 (KHTML, like Gecko) Comodo_Dragon/9.0.0.3 Chrome/9.0.597.98 Safari/534.13
```
As long as there is no source confirmed stating that "Comodo_Dragon" is a predecessor of "Dragon" I would leave the things as they are.
