### ISSUE TITLE
specification.md out of date with respect to devices

### ISSUE THREAD

**Issue by mspiegel** [ua-parser/uap-core#21]
The section on device_parsers lists 'family_replacement', 'brand_replacement', and 'model_replacement' fields. After commit 22ef8a1eabf930b9756244595a782ac0f2ad1a00 it looks like devices has the fields 'device_replacement', 'brand_replacement', and 'model_replacement'. Also it seems like all devices have all three fields explicitly enumerated and there doesn't appear to be an implicit match ordering as with the user_agent or operating system section. Is the documentation out of date?

**Comment by mspiegel** [comment]
Maybe device_replacement should be family_replacement in the yaml file?

**Comment by mspiegel** [comment]
Or maybe device_replacement remains as is. And there is a field labelled 'device' that lives under the group 'device'. I am unclear of the intent behind the most recent change.

**Comment by tobie** [comment]
@mspiegel Thanks for your reports, is that the same issue as the one you brought up on the mailing list?

**Comment by mspiegel** [comment]
yeah. I think I phrased the question better on the mailing list. I can close this ticket out.

**Comment by tobie** [comment]
See [mailing list thread](https://groups.google.com/forum/#!topic/ua-parser/SblRL79PlCA).
