### ISSUE TITLE
Chrome build version not parsed

### ISSUE THREAD

**Issue by znarf** [ua-parser/uap-core#22]
Chrome versions are based on 4 numbers (like 39.0.2171.95) but only the first 3 are currently parsed. Like that:

```
  "major" => "39",
  "minor" => "0",
  "patch" => "2171"
```

I see 2 potential solutions:

Skip the second number in Chrome which is usually always 0. It would result as:

```
  "major" => "39",
  "minor" => "2171",
  "patch" => "95"
```

This would unfortunately break applications that actually rely on the existing mapping.

The second solution is to introduce _patch_minor_ for all user agents. This is already existing for the os parser, so this would be logic and consistent.

```
  "major" => "39",
  "minor" => "0",
  "patch" => "2171",
  "patch_minor" => "95"
```

I understand this would be a major change, but think it's worth it.

What do you think?

**Comment by russellwhitaker** [comment]
Sounds like a very good idea to me.

**Comment by rishibansal** [comment]
+1

**Comment by hamiltop** [comment]
We already have 4 layers of versions for browsers. What's keeping this from being added?

**Comment by atomicopossum** [comment]
+1 This is old, but still an issue for my use case.
