### ISSUE TITLE
Ubuntu Chromium and Firefox device issue

### ISSUE THREAD

**Issue by 2tunnels** [ua-parser/uap-core#220]
Device family is `Other` for this two user agents:

Chromium:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36
```

Firefox:

```
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:51.0) Gecko/20100101 Firefox/51.0
```

Can we assume that Ubuntu is a desktop device? I know there are Ubuntu phones and tables, but we can think about those 3 individuals later :smiling_imp:

**Comment by commenthol** [comment]
Question to **all** - was or is there a specific reason not to attribute Desktop Devices as proposed?
