### ISSUE TITLE
should we consider masscan as a bot?

### ISSUE THREAD

**Issue by jnozsc** [ua-parser/uap-core#222]
the ua is 'masscan/1.0 (https://github.com/robertdavidgraham/masscan)'

>>> from user_agents import parse
>>> ua_string ='masscan/1.0 (https://github.com/robertdavidgraham/masscan)'
>>> user_agent = parse(ua_string)
>>> user_agent.is_bot
False
>>>

**Comment by commenthol** [comment]
for sure...

**Comment by jnozsc** [comment]
PR is ready for review

**Comment by jnozsc** [comment]
pr is merged, mark as done
