### ISSUE TITLE
Why os is android and browser is safari ?

### ISSUE THREAD

**Issue by littlejin** [ua-parser/uap-core#227]
Hi All,

I use uap-core to parse the following user agents,

Mozilla/5.0 (Linux; U; Android 2.3.6; zh-cn; HS-E912 Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1

Mozilla/5.0 (Linux; U; Android 7.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 UCBrowser/11.4.2.936 Mobile Safari/537.36

Mozilla/5.0 (Linux; Android 5.1.1; OPPO R7sm Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/35.0.1916.138 Mobile Safari/537.36 T7/7.4 baiduboxapp/8.2.5 (Baidu; P1 5.1.1)

it shows browser is safari and os is android, I think that's weird , is this a bug or something ?

Thanks

**Comment by ThaDafinser** [comment]
What is your expected result? Results from uap-core looks good.

> Mozilla/5.0 (Linux; U; Android 7.0; zh-CN; HUAWEI NXT-AL10 Build/HUAWEINXT-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/40.0.2214.89 UCBrowser/11.4.2.936 Mobile Safari/537.36

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+U%3B+Android+7.0%3B+zh-CN%3B+HUAWEI+NXT-AL10+Build%2FHUAWEINXT-AL10%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F40.0.2214.89+UCBrowser%2F11.4.2.936+Mobile+Safari%2F537.36


> Mozilla/5.0 (Linux; Android 5.1.1; OPPO R7sm Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/35.0.1916.138 Mobile Safari/537.36 T7/7.4 baiduboxapp/8.2.5 (Baidu; P1 5.1.1)

http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Linux%3B+Android+5.1.1%3B+OPPO+R7sm+Build%2FLMY47V%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F35.0.1916.138+Mobile+Safari%2F537.36+T7%2F7.4+baiduboxapp%2F8.2.5+%28Baidu%3B+P1+5.1.1%29

**Comment by littlejin** [comment]
I don't understand why android system will have safari as browser, I thought safari only exists in IOS system

**Comment by commenthol** [comment]
Can't reproduce the stated issues.
```
$ node tests/sample.js "Mozilla/5.0 (Linux; U; Android 2.3.6; zh-cn; HS-E912 Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1"
Results {
  userAgent: 'Mozilla/5.0 (Linux; U; Android 2.3.6; zh-cn; HS-E912 Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
  ua: { family: 'Android', major: '2', minor: '3', patch: '6' },
  os: 
   { family: 'Android',
     major: '2',
     minor: '3',
     patch: '6',
     patchMinor: null },
  device: { family: 'Hisense HS-E912', brand: 'Hisense', model: 'HS-E912' }}
```
Please make sure you have a recent `regexes.yaml` file included in your project.
