### ISSUE TITLE
UC Browser 11 not detected correctly

### ISSUE THREAD

**Issue by matthewsuan** [ua-parser/uap-core#236]
So i was lookng at #163 and it only tackles UC v5.. UC is now at 11 and is not detected properly

**Comment by commenthol** [comment]
Hi @matthewsuan, can you please share the User-Agent UC@11 to check the Issue here. Thanks.

**Comment by matthewsuan** [comment]
@commenthol here is the UA:
Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; SM-T800 Build/MMB29K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.8.945 U3/0.8.0 Mobile Safari/534.30

**Comment by commenthol** [comment]
Strange. The results correctly detect the UA as major 11. Please check using the latest regexes file.
```
Results {
  userAgent: 'Mozilla/5.0 (Linux; U; Android 6.0.1; en-US; SM-T800 Build/MMB29K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 UCBrowser/11.2.8.945 U3/0.8.0 Mobile Safari/534.30',
  ua: { family: 'UC Browser', major: '11', minor: '2', patch: '8' },
  os: 
   { family: 'Android',
     major: '6',
     minor: '0',
     patch: '1',
     patchMinor: null },
  device: { family: 'Samsung SM-T800', brand: 'Samsung', model: 'SM-T800' } }
```
