### ISSUE TITLE
Test for Safari/12602.2.14.0.7 CFNetwork/807.1.3 Darwin/16.1.0 (x86_64) failing

### ISSUE THREAD

**Issue by F21** [ua-parser/uap-core#238]
I updated the Go library to the latest commit (5dceb896913fc953d52881bf77e6ed64fd1b4054): https://github.com/ua-parser/uap-go/pull/41

Unfortunately, the test is failing for this UA: `Safari/12602.2.14.0.7 CFNetwork/807.1.3 Darwin/16.1.0 (x86_64)`:
```
got uaparser.Device{Family:"iOS-Device", Brand:"Apple", Model:"iOS-Device"}
want uaparser.Device{Family:"Other", Brand:"", Model:""}
```

I am not sure if this is an issue with `uap-core` (all tests appear to be passing here) or an issue with the go library.

**Comment by elsigh** [comment]
This seems like it must then be an issue in the Go library, perhaps related to https://github.com/ua-parser/uap-go/issues/33?

**Comment by F21** [comment]
@elsigh That might be the cause! I'll take a look at it when I find some time and will close this issue.

**Comment by Plasma** [comment]
@elsigh I'd like to point out https://github.com/ua-parser/uap-csharp/issues/23 which has failures as well due to the recent additions of at least one of the regexes to the core yaml file.

See https://github.com/ua-parser/uap-core/pull/230/files#r113348068
