### ISSUE TITLE
Support the new IE preview

### ISSUE THREAD

**Issue by 3rd-Eden** [ua-parser/uap-core#24]
A new monster UA has emerged:

> Mozilla/5.0 (Windows NT 6.4; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0

Seems to me that the best way to detect this monster is to assume that `Edge/12.0` is assumed as IE 12 and that other browser occurrences are ignored. 

Source: 
https://gist.github.com/jacobrossi/c9699b27df2f4e97c0bd
http://blogs.msdn.com/b/ie/archive/2014/11/11/living-on-the-edge-our-next-step-in-interoperability.aspx#10572654

**Comment by Ironholds** [comment]
Is Edge not supported? Huh. I thought I'd written that logic in.

**Comment by d10** [comment]
Yep, [it is supported](https://github.com/ua-parser/uap-core/blob/master/regexes.yaml#L267-269).

**Comment by 3rd-Eden** [comment]
Ahh, I see what's wrong then. I'm had a out of date file symlinked when I was testing. Apologies for the confusion <3!
