### ISSUE TITLE
Recent rexeges.yaml changes causing downstream failures

### ISSUE THREAD

**Issue by Plasma** [ua-parser/uap-core#240]
Hello,

I wanted to highlight this issue https://github.com/ua-parser/uap-csharp/issues/23

It appears caused by this commit https://github.com/ua-parser/uap-core/commit/4fb556e84804144b29f49f52f550d3f6d14cd9d0 in uap-core project.

Likely also causing issues for https://github.com/ua-parser/uap-core/issues/238

**Comment by commenthol** [comment]
A fix is on its way. Could you please test #241 with csharp parser? Thanks.

**Comment by Plasma** [comment]
Confirmed fixed
