### ISSUE TITLE
Case insensitive parsing

### ISSUE THREAD

**Issue by irfanyasin** [ua-parser/uap-core#243]
Hi
During testing I have noticed that the parsing is case sensitive. We have a use case where we are parsing some legacy user agents that have been transformed to lowercase. These are failing, however if they are correctly capitalised then they are parsed correctly.

Fails
`mozilla/5.0 (android; mobile; rv:30.0) gecko/30.0 firefox/30.0`

Works
`Mozilla/5.0 (Android; Mobile; rv:30.0) Gecko/30.0 Firefox/30.0`

Is there any reason why the parser is not case insensitive?

**Comment by josealvarezmuguerza** [comment]
question for u, did you receive the entire user string  in lowercase? if yes, make sure it is not a fake request mimicking a Firefox browser

**Comment by irfanyasin** [comment]
The user agent in question is from event data tracking video playback.
There are multiple events and they do follow the patterns inherent to real
events. So I don't think it is fake requests.

As it is older data I cannot confirm that it was received in lower case.

The user agent I posted is just one of quite a few different ones we have.


On 10 May 2017 1:14 pm, "jose alvarez muguerza" <notifications@github.com>
wrote:

question for u, did you receive the entire user string in lowercase? if
yes, make sure it is not a fake request mimicking a Firefox browser

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ua-parser/uap-core/issues/243#issuecomment-300463506>,
or mute the thread

**Comment by josealvarezmuguerza** [comment]
mm usually the Firefox's user agent string follows that Camel case format. Be sure you don't have a middleware code which lowercase the string

**Comment by irfanyasin** [comment]
That could be the case. The affected events were processed by a legacy
system which is no longer in production.

Unfortunately​ I can't check to see if that was the case as that code base
no longer exists.

Is there anything inherently wrong with supporting lower case user agents?

**Comment by commenthol** [comment]
> Is there anything inherently wrong with supporting lower case user agents?

No of course not. Your lowercase edge case simply does not match the "real" world. We are trying to identify real user agents and these are case sensitive nearly all cases. You can surely change the regexes.yaml file to match your needs. `regex_flag: 'i'` would be your friend here.
