### ISSUE TITLE
okhttp as bot?

### ISSUE THREAD

**Issue by josealvarezmuguerza** [ua-parser/uap-core#244]
Hi, how do u know okhttp is a Bot itself? it is a HTTP client for JAVA and Androids applications, so, a mobile developer could use that library in order to create its own apk and that should not be considered as an HTTPBot. I wonder why we definitively classify it as htttpbot ?

**Comment by commenthol** [comment]
Results of the current regexes file give me:
```
$ node tests/sample.js "okhttp/3.4.2"
Results {
  userAgent: 'okhttp/3.4.2',
  ua: { family: 'okhttp', major: '3', minor: '4', patch: '2' },
  os: 
   { family: 'Other',
     major: null,
     minor: null,
     patch: null,
     patchMinor: null },
  device: { family: 'Other', brand: null, model: null } }
```
Can you please clarify what you mean with okhttp being classified as bot? 
#185 just added detection for okhttp but did no classification in the devices section.

**Comment by josealvarezmuguerza** [comment]
my bad ,  I was reviewing a wrong fork
