### ISSUE TITLE
how to use this in js?

### ISSUE THREAD

**Issue by RifeWang** [ua-parser/uap-core#246]
Can i import this  library like jquery to my project? like this:
```
<script src="http://cdn.staticfile.org/jquery/1.8.3/jquery.min.js"></script>
```
And how to use it , for example ， i want to test userAgent to kown my user's device vendor like Huawei , how can i do ?

**Comment by commenthol** [comment]
This library is intended for nodejs use only. There is no intent to run this in the browser.
