### ISSUE TITLE
iOS 11 CFNetwork/Darwin detection

### ISSUE THREAD

**Issue by longzheng** [ua-parser/uap-core#278]
Now that iOS 11 is publically available, the regexes for CFNetwork/Darwin version specific matching can be updated to target iOS 11.

Sample useragent

```
Instacast/2749 CFNetwork/887 Darwin/17.0.0
PodCruncher/3.3.1 CFNetwork/887 Darwin/17.0.0
Castro/516 CFNetwork/887 Darwin/17.0.0
```

**Comment by khamin** [comment]
Hello, let us know if #289 fixes the problem

**Comment by longzheng** [comment]
👍

**Comment by khamin** [comment]
You can close it then ;)
