### ISSUE TITLE
Specify regex dialect in specification.md

### ISSUE THREAD

**Issue by davemarchevsky** [ua-parser/uap-core#28]
I'm working on https://github.com/ua-parser/uap-go/issues/6. In the process of implementing a potential fix (adding some new struct fields), I saw this error while testing against the latest version of `regexes.yaml` and `test_resources`:

``` go
panic: regexp: Compile(`; *(?:ARCHOS|Archos) ?(GAMEPAD(?:(?! Build|[;/\(\)\-]).)*)`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

Ideally `specification.md` would point to a spec (pcre perhaps?) that all regexes in `regexes.yaml` must conform to so parser implementations can use the appropriate library for their language.

**Comment by commenthol** [comment]
Is solved with #64. Negative lookaheads are removed.
