### ISSUE TITLE
Helping maintain the project

### ISSUE THREAD

**Issue by sunknudsen** [ua-parser/uap-core#299]
Hey,

Would like to help maintain uap-core.

I see https://www.npmjs.com/package/useragent relies on https://raw.githubusercontent.com/ua-parser/uap-core/master/regexes.yaml.

I use useragent to parse user agents at Lickstats and I'm seeing some hits not labelled as spiders that are spiders. Just submitted a pull request to add them to the regexes.

Also, would like to submit a pull request to https://github.com/3rd-Eden/useragent adding documentation on where regexes.yaml originates from to help the community submit additions and updates to uap-core.

Hope I can help.

Best,

Sun

**Comment by tobie** [comment]
Gav you commit access. Thanks for reaching out.
