### ISSUE TITLE
Feed Crawlers

### ISSUE THREAD

**Issue by tofias** [ua-parser/uap-core#308]
Has there been any consideration of adding the ability to extract subscriber data and other information which certain crawlers like feed readers (like Feedbin, Feed Wrangler, some of the podcast services, etc.) put into their user agent strings?

For example a Feedbin user agent string looks something like this

> "Feedbin feed-id:07263a2 - 77 subscribers"

Currently, I'm just doing the extraction in my code, but thought it would be nice to push into ua-parser instead of basically parsing all of the strings twice.

**Comment by tobie** [comment]
That’s really out of scope and warrants a dedicated module.
