### ISSUE TITLE
Add support for device type

### ISSUE THREAD

**Issue by budadcabrion** [ua-parser/uap-core#31]
Similar to the request from @mspiegel--

I'd like to be able to identify the type or category of the device, or at least test if the device belongs to current broad categories, like is-a-phone or is-a-tablet.

**Comment by devdazed** [comment]
:+1: I have a branch going at: simplereach/uap-core@612715029a434013b8da6b142169cec9a822b552. I want to make it a PR, but lack the resources to update all of the tests and the rest of the projects. Plus some of the devices may be miscategorized.

**Comment by elsigh** [comment]
In general uap-core doesn't want to do device "type" detection for a slew
of reasons (what does it mean to be "mobile". Is a tablet that makes a
calls a "phone"?)

**Comment by devdazed** [comment]
With the rising trend in tablet usage, currently accounting for roughly 10%-15% of overall web traffic, people will want more insight into what type of device it is to better the end user's experience. 

From what I have seen in other detection systems the device type doesn't necessarily need to be mutually exclusive. For instance, [AWS will categorize something as both mobile and tablet](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-device) if the device meets criteria for both.  I would also like to add that device "type" confusion is only around tablet vs. mobile, all other devices generally tend to be mutually exclusive, (eg. a TV can not be a car etc).  While some of the items are rather subjective, I am sure a consensus can be made on how the item should be categorized.  

Lastly all major analytics solutions currently differentiate between mobile and tablet traffic, so this is not untrodded ground. I am not sure why UAP is apprehensive to the idea.

**Comment by elsigh** [comment]
This is why there are tools based on uap =) I agree it's valuable, but it's
enough into the realm of "using a string not in the UA" that we don't want
to do it in uap.

**Comment by devdazed** [comment]
Are you suggesting that it is impossible to determine the device type with the UA alone?

**Comment by elsigh** [comment]
I'm saying that what you mean by "determine the device" and what someone
else means by "determine the device" are not necessarily the same.

**Comment by devdazed** [comment]
so you mean that, because  someone has to say it is a tablet and it isn't written "this is a tablet" in the UA itself, then it beyond the bounds of this project?

**Comment by elsigh** [comment]
Basically. This project exists to solve a parsing/normalization issue wrt
user agent strings. And just doing that, it's surprisingly complex. Adding
"intelligence" and semantics beyond the user agent string is something we
used to have in the project and backed out of it. You can look through some
of that history on the original repo too =) github.com/tobie/ua-parse

**Comment by devdazed** [comment]
fair enough, I can see how adding this type of subjective detection would not be suitable for this project.
