### ISSUE TITLE
Edge mobile is detected as Chrome on iOS and Android

### ISSUE THREAD

**Issue by ogvolkov** [ua-parser/uap-core#328]
Mozilla/5.0 (iPad; CPU OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0 EdgiOS/42.2.2.0 Mobile/15D100 Safari/604.5.6

Mozilla/5.0 (Linux; Android 7.0; SM-G955F Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.109 Mobile Safari/537.36 EdgA/42.0.0.2057

UserAgent.Family is detected as Chrome currently

**Comment by mgol** [comment]
Related: #396 as the new Chromium-based Edge also uses a different token (`Edg/` instead of `Edge/`).

**Comment by Tigraine** [comment]
In my testing with the latest version `uap-go` commit `ac4b80194e5b` this has been fixed and 

`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.19 Safari/537.36 Edg/77.0.235.9"` correctly returns `Edge`

**Comment by Tigraine** [comment]
The mobile user agent from https://www.whatismybrowser.com/guides/the-latest-user-agent/edge doesn't work with the latest version right now.

```
Mozilla/5.0 (Windows Mobile 10; Android 8.0.0; Microsoft; Lumia 950XL) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.111 Mobile Safari/537.36 Edge/40.15254.369
```

Also gets reported as `Chrome Mobile` with `uap-go`: `ac4b80194e5b`
