### ISSUE TITLE
Important amount of iOS users with "Snapchat" UA not detected as Safari

### ISSUE THREAD

**Issue by Grsmto** [ua-parser/uap-core#337]
Hi guys,

I received a lot of reports from users not being detected properly (83 users exactly at the moment):
![screen shot 2018-08-13 at 22 32 47](https://user-images.githubusercontent.com/527559/44066830-dfb5686c-9f48-11e8-8aba-8903c13d2fb5.jpg)

And they all come with the exact same following UA:
`Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_6 like Mac OS X) AppleWebKit/604.5.6 (KHTML, like Gecko) Snapchat/10.38.0.25 (iPhone8,1; iOS 11.2.6; gzip)`

(notice the **Snapchat** there 😅)
Also Sentry is reporting the `browser` prop as being `AppleMail 605.1.15`. I'm not sure where it comes from exactly and what iphone app it is but It seems like this UA is being parsed as `ios_saf/0.0.0` whereas from what I see it's a Mobile Safari UIWebView.

Could you please let me know if I'm right and if I could do a PR for this?

Thanks!

**Comment by chee** [comment]
@longzheng How come we're capturing the Snapchat/`version-number` here rather than the `11.2.6`.

This is a iOS Safari webview and i think we'd probably want the semver from iOS Safari rather than the Snapchat version

**Comment by chee** [comment]
This seems to take the same format as the AppleNews line here https://github.com/121cast/uap-core/blob/5f86e20cb99c6ac684ab340ec15bd6520cf02e30/regexes.yaml#L621-L622

but with `Snapchat` in place of `AppleNews`.

**Comment by longzheng** [comment]
> @longzheng How come we're capturing the Snapchat/`version-number` here rather than the `11.2.6`.

`11.2.6` is the iOS version in the example useragent. `10.38.0.25` is the version of the Snapchat app.

The regex added for Snapchat is to detect the app name and version. The OS name and version is handled separately by a different regex section.
