### ISSUE TITLE
Instagram uses Chrome but is parsed as Mobile Safari

### ISSUE THREAD

**Issue by bluesmoon** [ua-parser/uap-core#35]
This is the user agent string: 

`Instagram 3.4.1 (iPhone5,1; iPhone OS 6.0.2; en_US; en) AppleWebKit/420+`

This is what it gets parsed as:
`{"family":"Mobile Safari","os":"iOS","osversion":"6"}`

This is how I know it is Chrome:

`window.performance.memory.usedJSHeapSize` is set (in JavaScript)

**Comment by richardthombs** [comment]
I thought all iOS apps had to use the built in Safari web view. Even Google Chrome on iOS has to.

**Comment by bluesmoon** [comment]
interesting.  However Safari doesn't implement `window.performance`, so this cannot be Safari.

**Comment by nerdbaggy** [comment]
I am seeing this same issue as well, the user agent
```
Instagram 7.8.0 (iPhone5,3; iPhone OS 9_0_2; en_US; en-US; scale=2.00; 640x1136) AppleWebKit/420+
```
Gets parsed as
```
"user_agent" : {
        "name" : "Mobile Safari UIWebView",
        "os" : "iOS 9.0.2",
        "os_name" : "iOS",
        "os_major" : "9",
        "os_minor" : "0",
        "device" : "iPhone5,3"
    }
```

**Comment by commenthol** [comment]
Please keep in mind that uaparser only parses strings. 
We do not know if all/any Instagram Browsers relies on Chrome (Engine). I am missing a reference to verify this point. uaparser is not intended to do client side testing - so therefore we would need a "distinctive mark" in this string to associate.
If "Instagram" on its own can be seen as a UA (what it is in my opinion), then we should add a rule which allows us to identify it as such.
