### ISSUE TITLE
Windows 8.1

### ISSUE THREAD

**Issue by thyn** [ua-parser/uap-core#351]
Issue from  https://github.com/thyn/ua-parser-formfactor/issues/2

Could you please fix it on your side. I also think that windows 8.1 is minor release.

Text of issue:

Noticed something weird that Windows 8.1 user-agent strings are not parsed.

Examples of those that seem to fail:
```
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
```
For Windows 8.1 with "Windows NT 6.3" userAgent, the ua-parser sets Major to an "8.1" float when it should be Major "8" integer and Minor "1" integer.

Code on our side does an int() conversion on Major and fails.

**Comment by commenthol** [comment]
Hi @thyn, 
this should be fixed with #371.
