### ISSUE TITLE
PTST/SpeedCurve and PTST/1.0 not identified as a Spider

### ISSUE THREAD

**Issue by kingo55** [ua-parser/uap-core#364]
We're seeing swathes of Spider traffic misclassified. #319 seems to be related to this too... Would you guys be open to a PR?

```
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.0 Safari/537.36 PTST/1.0
```

```
Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko PTST/1.0
```

https://support.speedcurve.com/testing-process/how-do-the-browser-testing-agents-work

**Comment by commenthol** [comment]
Thanks
