### ISSUE TITLE
New user agents not supported

### ISSUE THREAD

**Issue by SrdjanNikitovic** [ua-parser/uap-core#374]
Hello there.

We have a problem that new user agents are not parsed correctly in Python.
After looking investigating the regexes.yaml file, we see that Python library is pointing to a 10 month old commit of uap-core, but the most recent version of uap-core is 10 days old.

Is there a reason why old uap-core is used, or we can use the new one?

**Comment by commenthol** [comment]
please report issue in python parser project.
