### ISSUE TITLE
device_replacement allowed in user_agent_parsers?

### ISSUE THREAD

**Issue by neilcook** [ua-parser/uap-core#377]
Commit 8f247bee2cebad8b8e075767465639c875b3e6b1

added the following device_replacement line:

  # PTST / WebPageTest.org crawlers
  - regex: ' (PTST)/(\d+)\.(\d+)$'
    family_replacement: 'WebPageTest.org bot'
    device_replacement: 'Spider'
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Is this legal? Certainly uap-cpp barfs on this line, as it is not expecting device_replacement in user_agent_parers.

**Comment by kingo55** [comment]
That would be my bad. How should I have handled this @neilcook ?

**Comment by neilcook** [comment]
so user-agent-parsers can only contain:
family_replacement
v1_replacement
v2_replacement
v3_replacement

If you want to replace the device, the parser needs to be part of device_parsers.

**Comment by kingo55** [comment]
Thanks for letting me know @neilcook . Still learning the ropes here... I've pushed a fix to address this issue.

Perhaps we also need a new test to check the replacement fields so this won't impact other contributors.
