### ISSUE TITLE
Windows 10 is not detected

### ISSUE THREAD

**Issue by yozik04** [ua-parser/uap-core#41]
Windows 10:
UA: "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0"

Xbox One:
UA: "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0; 
 Xbox; Xbox One)"

Xbox 360:
UA: "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; 
 Xbox)"

**Comment by yozik04** [comment]
pull request #42

**Comment by commenthol** [comment]
Windows 10.0 should be detected now (#42 is merged). What's with the Xbox UAs?

**Comment by commenthol** [comment]
@yozik04 Any update on this?

**Comment by mzgol** [comment]
Edge is now supported by uap-core, a submodule update should be enough?
