### ISSUE TITLE
Normalise test case YAML files

### ISSUE THREAD

**Issue by clarfon** [ua-parser/uap-core#410]
Right now, the YAML files for the test cases don't convey whether they're testing device, OS, or browser except via the file name. It'd be nice if these could be normalised and maybe unified into one file so that an implementation could simply write one test runner and run every YAML file through it.

What I'm thinking is that the root is still `test_cases`, but within each case, you have a separate `device`, `os`, and `browser` section that indicates what values are being checked.

This mostly came about because I've been working on [nginx-uaparser-module](https://github.com/clarfon/nginx-uaparser-module) and mostly trying to figure out how to test the implementation.

**Comment by commenthol** [comment]
I think that has historical reasons. Feel free to concatenate the tests and use it in your parser. Please check tests/test.js for concatenation the right files.

**Comment by clarfon** [comment]
So… would you accept a pull request making this change to the project directly?
