### ISSUE TITLE
Incorrect model detection when using Firefox Mobile on Android

### ISSUE THREAD

**Issue by murderotica** [ua-parser/uap-core#423]
User agent: `Mozilla/5.0 (Android 6.0.1; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0`
Offending regex: 
https://github.com/ua-parser/uap-core/blob/286809e09706ea891b9434ed875574d65e0ff6b7/regexes.yaml#L5312

Model is detected as `rv:65.0`. Previous regex `Android[\- ][\d]+(?:\.[\d]+){1,2}(?:;.*)?; *(.+?) Build[/ ]` would correctly not detect it as a model.

**Comment by commenthol** [comment]
This is what I get here 

```
node tests/sample.js "Mozilla/5.0 (Android 6.0.1; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0"
Results {
  userAgent: 'Mozilla/5.0 (Android 6.0.1; Mobile; rv:65.0) Gecko/65.0 Firefox/65.0',
  ua: { family: 'Firefox Mobile', major: '65', minor: '0', patch: null },
  os: {
    family: 'Android',
    major: '6',
    minor: '0',
    patch: '1',
    patchMinor: null
  },
  device: {
    family: 'Generic Smartphone',
    brand: 'Generic',
    model: 'Smartphone'
  }
}
```
Looks ok for me...

**Comment by murderotica** [comment]
This was reported almost half a year ago. So it seems to have been fixed sometime in that period as it works on master (and in fact none of Generic_Android regexes match this UA anymore).
