### ISSUE TITLE
Android Motorola E4 Plus is getting detected as Tablet and Desktop device type

### ISSUE THREAD

**Issue by mayanksourabh** [ua-parser/uap-core#426]
User-agent from device is:
Dalvik/2.1.0 (Linux; U; Android 7.1.1; Moto E (4) Plus Build/NMA26.42-169)

ua parser result:
Device Model: E (4) Plus
Device Brand: Motorola
OS Major: 7
OS Minor: 1
OS Patch: 1
OS Patch Minor: 
OS String: Android 7.1.1
OS Version String: 7.1.1
Browser Major: 7
Browser Minor: 1
Browser Patch: 1
Browser Patch Minor: 
Browser String: Android 7.1.1
Browser Version String: 7.1.1
Full String: Android 7.1.1/Android 7.1.1
**Device Type : Tablet**

===============================================================
User-agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36

ua-parser result
OS String: Linux 0.0.0
OS Version String: 0.0.0
Browser Major: 52
Browser Minor: 0
Browser Patch: 2743
Browser Patch Minor: 82
Browser String: Chrome 52.0.2743
Browser Version String: 52.0.2743
Full String: Chrome 52.0.2743/Linux 0.0.0
**Device Type : Desktop**

**Comment by commenthol** [comment]
@mayanksourabh Unfortunately we only can detect what we get as an input. The later does not give us any hint on "Motorola E4 Plus", so what do you recommend?
