### ISSUE TITLE
package is not published to npm

### ISSUE THREAD

**Issue by fedot** [ua-parser/uap-core#43]
Is there a good reason not to have the `uap-core` in npm registry?

**Comment by TheSavior** [comment]
:+1: Would be really nice to have this actually published so we can use it from other projects.

**Comment by elsigh** [comment]
@fedot

**Comment by TheSavior** [comment]
Why don't we just set up travis to auto deploy on a successful build on master when the version has been updated?

**Comment by fedot** [comment]
@elsigh I'm fine with doing this by hand but pretty sure this task better to be automated with Travis CI [npm Releasing](https://docs.travis-ci.com/user/deployment/npm), which should be quite easy to roll up.

@TheSavior +1, would love it
