### ISSUE TITLE
[bug] Parsing fails due to lacking "Build/"

### ISSUE THREAD

**Issue by devrimcavusoglu** [ua-parser/uap-core#444]
Parser fails to parse device model for the user agents like the following;

`Mozilla/5.0 (Linux; Android 7.0; SM-J701F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.73 Mobile Safari/537.36`

`#parser returns`
`{'family': 'Generic Smartphone', 'brand': 'Generic', 'model': 'Smartphone'}`

as I researched a bit, "regexes.yaml" file contains `Build/` for many regexes, and although device model can be directly parsed from the user agent above as `SM-J701F`, it cannot be parsed since it does not have `Build/` clause in it.

**Comment by commenthol** [comment]
Please check v0.7.1
