### ISSUE TITLE
Version Overview

### ISSUE THREAD

**Issue by einhorntee** [ua-parser/uap-core#445]
It is very hard to figure out which core version the newest release of any ua-parser actually depends on.
Would it be possible to add some kind of documentation/overview?

Explanation: I want to use the java as well as the python ua-parser, and obviously have them use the same core version. I originally thought this was a no-brainer, but the different release cycles, version naming and git submodules are making this really complicated.

Suggestion:
Add something like this to the readme

| Core Version  | Releases  |
|---|---|
| 0.9.10  | java 1.4.??? , cpp ???, go ???  | 
| 0.5.0  | java 1.???, python 0.8.0, go ???  |

or to any readme of each parser (example for python)

| Release/Version  | Core Version  |
|---|---|
| 0.8.0 | 0.5.0  | 
| 0.7.3  | 0.5.0  |

**Comment by commenthol** [comment]
This is just the repo for the regex lists used by the different parsers. Please get back to the different parser maintainers to document their used version. We now use version tags which should allow the different parser maintainers to grab the latest version either via npm or git.
