### ISSUE TITLE
Test issue with latest regexes

### ISSUE THREAD

**Issue by pseverino** [ua-parser/uap-core#450]
I did a pull for the latest data and it looks like the project's tests are failing with it:

`  31933 passing (9s)
  2 failing

  1) ../tests/test_ua.yaml
       Twitterbot/1.0:

      AssertionError [ERR_ASSERTION]: Expected ua.family to be "TwitterBot" got "Twitterbot" instead.
      + expected - actual

      -Twitterbot
      +TwitterBot
      
      at Context.<anonymous> (tests/test.js:25:16)
      at processImmediate (internal/timers.js:439:21)

  2) ../test_resources/pgts_browser_list.yaml
       fetch libfetch/2.0:

      AssertionError [ERR_ASSERTION]: Expected ua.family to be "Other" got "fetch libfetch" instead.
      + expected - actual

      -fetch libfetch
      +Other
      
      at Context.<anonymous> (tests/test.js:25:16)
      at processImmediate (internal/timers.js:439:21)`

**Comment by commenthol** [comment]
@pseverino [travis](https://travis-ci.org/ua-parser/uap-core) says tests are fine. Could you please check at your side?

**Comment by pseverino** [comment]
You're right, after searching thought a bunch of logs I found out that the tests that were created internally by us with your tests weren't actually getting updated.

A simple case of docker cache, thanks for checking and sorry for the trouble
