### ISSUE TITLE
User agent from iPads - CPU iPad OS 

### ISSUE THREAD

**Issue by nitayk** [ua-parser/uap-core#502]
Fails on:
"Mozilla/5.0 (iPad; CPU iPad OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"

**Comment by masklinn** [comment]
@lbarthon @migueldemoura I think this issue was fixed but forgotten about, there's a linked commit which was merged in from PR #503 but the stricture is incorrect, and so the issue was never closed.

**Comment by lbarthon** [comment]
@masklinn the structure is incorrect, meaning? the example UA sgtm?

**Comment by masklinn** [comment]
> the structure is incorrect, meaning? the example UA sgtm?

No no str_i_cture, the original PR used “fix issue #502” which GitHub does not recognize. Commenthol might have seen it and assumed it would work.

**Comment by lbarthon** [comment]
Oh I see, will close then!
TIL: stricture
