### ISSUE TITLE
Request to add PetalBot (formerly AspiegelBot)

### ISSUE THREAD

**Issue by gnikolaidis** [ua-parser/uap-core#525]
This is a very aggressive spider from China. Formerly known as AspiegelBot ([source](https://www.hypernode.com/blog/huawei-aspiegelbot-is-increasingly-impacting-european-online-stores/)).

UA Parser splits it to:

- browser family: PetalBot
- os family: Android
- os version: 7.0
- device family: Generic Smartphone

It would be nice if it was tagged as a spider.

**Comment by not-implemented** [comment]
+1

... this is the current User-Agent-String:

`Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot;+https://webmaster.petalsearch.com/site/petalbot)`
