### ISSUE TITLE
'js_user_agent_string' not mentioned in specification

### ISSUE THREAD

**Issue by russellwhitaker** [ua-parser/uap-core#55]
'js_user_agent_string' and associated Chrome Frame related substitution alternates are apparently used in at least two ua-parser language implementations (Python and PHP) but are not addressed in the specification document for uap-core. Apparently there's historical context predating the languages/core split which is not documented in ua-parser/uap-core, which can cause puzzlement to developers new to the project (e.g. myself, with a Clojure implementation I'm bringing up to date on the specification w.r.t. Browser and O/S, as well as adding Device, PR pending.)

Does someone have guidance on this?

**Comment by elsigh** [comment]
I think you're free to consider js_user_agent_string a deprecated part of uap-core.

**Comment by russellwhitaker** [comment]
@elsigh thanks. OK, that would explain why the tests invoked in the `npm test` hooks for travis skip those tests with `:js_ua` members in `./tests/test_ua.yaml` per: https://github.com/ua-parser/uap-core/blob/master/tests/test.js#L21

I had to filter against these tests myself in the Clojure implementation I wrote because the family/major/minor/patch expectation values in `./tests/tests_ua.yaml` are in accord with the not-to-spec expectations of whichever implementations actually use `:js_ua`: https://github.com/russellwhitaker/uap-clj/blob/master/spec/uap_clj/core_spec.clj#L12

Those filtered tests:

```clojure
(def bad-tests-browser
  #{{:user_agent_string
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GTB6; .NET CLR 2.0.50727; .NET CLR 1.1.4322)",
  :js_ua
  "{'js_user_agent_string': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 1.1.4322)', 'js_user_agent_family': 'IE Platform Preview', 'js_user_agent_v1': '9', 'js_user_agent_v2': '0', 'js_user_agent_v3': '1'}",
  :family "IE Platform Preview",
  :major "9",
  :minor "0",
  :patch "1"}
    {:user_agent_string
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; chromeframe; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; Sleipnir 2.8.5)3.0.30729)",
  :js_ua
  "{'js_user_agent_string': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/530.1 (KHTML, like Gecko) Chrome/2.0.169.1 Safari/530.1'}",
  :family "Chrome Frame (Sleipnir 2)",
  :major "2",
  :minor "0",
  :patch "169"}
    {:user_agent_string
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; chromeframe; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)",
  :js_ua
  "{'js_user_agent_string': 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US) AppleWebKit/530.1 (KHTML, like Gecko) Chrome/2.0.169.1 Safari/530.1'}",
  :family "Chrome Frame (IE 8)",
  :major "2",
  :minor "0",
  :patch "169"}})
```
Here's what a specification-compliant implementation of browser, o/s, and device parsing says about those useragent strings:

```clojure
uap-clj.core=> (pprint (map #(lookup-useragent (:user_agent_string %)) bad-tests-browser))
({:ua
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; chromeframe; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; Sleipnir 2.8.5)3.0.30729)",
  :browser {:family "Sleipnir", :major "2", :minor "8", :patch "5"},
  :os
  {:family "Windows XP",
   :major "",
   :minor "",
   :patch "",
   :patch_minor ""},
  :device {:family "Other", :brand nil, :model nil}}
 {:ua
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; chromeframe; SLCC1; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729)",
  :browser {:family "IE", :major "8", :minor "0", :patch ""},
  :os
  {:family "Windows Vista",
   :major "",
   :minor "",
   :patch "",
   :patch_minor ""},
  :device {:family "Other", :brand nil, :model nil}}
 {:ua
  "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; GTB6; .NET CLR 2.0.50727; .NET CLR 1.1.4322)",
  :browser {:family "IE", :major "8", :minor "0", :patch ""},
  :os
  {:family "Windows XP",
   :major "",
   :minor "",
   :patch "",
   :patch_minor ""},
  :device {:family "Other", :brand nil, :model nil}})
```
Would you welcome a PR to fix the test fixture for these 3 cases with respect to browser? I have a recent track record of a previous fix to `rejexes.yaml`: https://github.com/ua-parser/uap-core/issues/51

**Comment by elsigh** [comment]
We should remove the js_user_agent_string entirely. ChromeFrame is long gone and it was a very unfortunate hack to have to detect it client-side. If you'd be cool with doing that bit of extra refactoring it'd be extra awesome. If not I understand and I'd still merge your change. Thanks!

**Comment by russellwhitaker** [comment]
I would be delighted to roll in that bit of refactoring @elsigh . Specifically, just to be clear, I should expunge all `:js_ua` payloads from `./tests/test_ua.yaml` and `./tests/test_os.yaml` and the "skip if js_ua" line in the core testrunner invoked by travis-ci? https://github.com/ua-parser/uap-core/search?utf8=✓&q=js_ua

**Comment by elsigh** [comment]
Yep, that sounds right to me. Once done, I'll nuke the relevant code in the python port.

**Comment by russellwhitaker** [comment]
@elsigh thanks, OK, will do this morning and will link to the PR here.

**Comment by russellwhitaker** [comment]
`npm test` worked locally for me on this change, and on the travis-ci build on my source fork branch. Looks like travis is taking its time to do the same here, hope it kicks off eventually...

**Comment by russellwhitaker** [comment]
OK, travis build successful.

**Comment by russellwhitaker** [comment]
Closing; fixed with: https://github.com/ua-parser/uap-core/pull/58
