### ISSUE TITLE
User-agent with EdgiOS mapped wrongly

### ISSUE THREAD

**Issue by cezarasoliveira** [ua-parser/uap-core#565]
As we can see below, the code `  - regex: '(EdgiOS|EdgA)/(\d+)\.(\d+)\.(\d+)\.(\d+)'
    family_replacement: 'Edge Mobile'` map `EdgiOS` as `Edge Mobile`.

This works well when we have a user-agent like this `Mozilla/5.0 (iPhone; CPU iPhone OS 17_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 EdgiOS/119.2151.65 Mobile/15E148 Safari/605.1.15`.

However, we received the user-agent `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/118 Version/13.0.3 Safari/605.1.15` that was mapped wrongly as `Safari 13.0.3` instead of `Edge Mobile 118`.

**Comment by lbarthon** [comment]
Fixed by https://github.com/ua-parser/uap-core/pull/558
