### ISSUE TITLE
regexes.yaml now has negative lookaheads (which break the uap-go implementation)

### ISSUE THREAD

**Issue by elsigh** [ua-parser/uap-core#63]
We've talked about performance before, but interestingly I wanted to use the uap-go implementation and found that some time between the version of uap-core that it's pinned to (99e8ba5df94d7af18576a8cc01d11ed9c45d8f86) and now there have been a fair number of negative lookaheads added to regexes.yaml. Golang doesn't implement negative lookaheads because they are slower than O(n). I'm sure there are some hacks the go implementation could make to deal with these, but maybe we shouldn't allow negative lookaheads in regexes.yaml for this reason? 
It may be that regexes.yaml isn't the place to enforce anything related to perf, but it's also true that negative lookaheads are kinda hard to digest (but then again, so is regex generally to many people).

**Comment by tobie** [comment]
I concur. They're definitely [hard to read](https://github.com/ua-parser/uap-core/blob/caf64e12a015b88968bc39f9ab92d43ae04da26f/regexes.yaml#L1181), and broad language support is also important.

**Comment by commenthol** [comment]
@elsigh can you please test this version with uap-go?

**Comment by MarkMoudy** [comment]
@commenthol Unsolicited but I gave this new regexes.yaml version a try with uap-go and it didn't work. 

The error I got was: ```error parsing regexp: invalid or unsupported Perl syntax: `(?!` ```  
Full Error Output: 
```shell
panic: regexp: Compile(`(008|Altresium|Argus|BaiduMobaider|BoardReader|DNSGroup|DataparkSearch|EDI|Goodzer|Grub|INGRID|Infohelfer|LinkedInBot|LOOQ|Nutch|PathDefender|Peew|PostPost|Steeler|Twitterbot|VSE|WebCrunch|WebZIP|Y!J-BR[A-Z]|YahooSeeker|envolk|sproose|wminer)/(\d+)(?:\.(\d+)(?:\.(\d+))?)?(?:(?!CFNetwork).)*$`): error parsing regexp: invalid or unsupported Perl syntax: `(?!`
```

**Comment by elsigh** [comment]
Sweet, fixed the uap-go implementation to support some new bits and tested that indeed the new yaml works for me =)

**Comment by elsigh** [comment]
@commenthol You good if we merge #64?

**Comment by elsigh** [comment]
Also, THANK YOU! My gosh, you're awesome.
