### ISSUE TITLE
Client type?

### ISSUE THREAD

**Issue by jnfeinstein** [ua-parser/uap-core#65]
Is there a way to retrieve the *type* (i.e. phone, tablet, laptop, desktop, etc) of a device using `ua-parser`?  [This](https://github.com/faisalman/ua-parser-js) alternate JavaScript library performs this by hardcoding the type depending on which regexes match.  I couldn't find anything like it in the `ua-parser` docs.

**Comment by mattbertolini** [comment]
+1 for this. It would be very helpful.

**Comment by elsigh** [comment]
I really need to write up a FAQ on this, it comes up periodically.

UA Parser is not going to get into the business of categorizing UAs one way or another. That's a task for other libraries/maintainers. This project's goal is strictly to parse and return normalized parts of the UA string.

See #31 for more discussion and tobie's original Issue tracker had this multiple times as well.

**Comment by jnfeinstein** [comment]
I see, thank you for the insight.

**Comment by mattbertolini** [comment]
Fair enough. Thanks for the context.
