### ISSUE TITLE
Facebook Mobile Browser

### ISSUE THREAD

**Issue by patmmccann** [ua-parser/uap-core#70]
I see "Mozilla/5.0 (Linux; Android 5.0.1; SCH-I545 Build/LRX22C; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/43.0.2357.121 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/38.0.0.47.240;]" parsing as Chrome but it should be the Facebook Browser.

**Comment by alexholy** [comment]
The UA contains "/FB4A" for Facebook/Android and "/FBIOS" for Facebook/iOS.

Example: 
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Mobile/12B466 [FBAN/FBIOS;FBAV/39.0.0.36.31;FBBV/14703842;FBDV/iPhone7,1;FBMD/iPhone;FBSN/iPhone OS;FBSV/8.1.3;FBSS/3; FBCR/T-MobileA;FBID/phone;FBLC/en_US;FBOP/5]

in this case the current rules misidentify the Device as "iPhone7,1"

**Comment by xiang90** [comment]
Hope we can support this one soon
