### ISSUE TITLE
Edge still detected as Chrome

### ISSUE THREAD

**Issue by croensch** [ua-parser/uap-core#72]
http://uaparser.dmolsen.com/
```
  ua->family: Chrome
  ua->major: 42
  ua->minor: 0
  ua->patch: 2311
  ua->toString: Chrome 42.0.2311
  ua->toVersionString: 42.0.2311
  os->family: Windows
  os->major: 
  os->minor: 
  os->patch: 
  os->patch_minor: 
  os->toString: Windows
  os->toVersionString: 
  device->family: Other
  toFullString: Chrome 42.0.2311/Windows
  uaOriginal: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.0
```
https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

**Comment by clexit** [comment]
You must be using the ua-parser version from pip. [This commit|https://github.com/ua-parser/uap-core/commit/87b6282f3e2792fc0bfb89f4a84397417329dbd0] works fine, but maybe pip hasn't been updated yet.

**Comment by croensch** [comment]
I'm actually not running that site, and also i use the older source [tobie/ua-parser](https://github.com/tobie/ua-parser) but with the exact regexes.yaml you linked. (I did compile it down.) Guess i have to setup a demo for the current source+yaml.

**Comment by croensch** [comment]
I've compiled it down yes, but i still had the wrong file in the app :frog: 

Fair warning tough: current regexes.yaml includes an "@" which is not escaped by tobie/ua-parser so the converted file must be fixed by writing "\\@" manually.

Should've just used composer...
