### ISSUE TITLE
Edge is being parsed as Chrome

### ISSUE THREAD

**Issue by AdrianoCahete** [ua-parser/uap-core#78]
I tested in some links i found:
http://www.whatsmyua.info/
http://uaparser.dmolsen.com/

Both shows:
```
rawUa: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 *Edge/12.10240*
string: *Chrome 42.0.2311*
family: *Chrome*
major: 42
minor:
patch: 2311
device: Other
```

```
ua->family: Chrome
  ua->major: 42
  ua->minor: 0
  ua->patch: 2311
  ua->toString: Chrome 42.0.2311
  ua->toVersionString: 42.0.2311
```

Is that links update with latest code? If no, do you have any?

**Comment by commenthol** [comment]
According to the tests Edge is detected correctly https://github.com/ua-parser/uap-core/blob/master/tests/test_ua.yaml#L1023
Seams that the services you tested require some update.
