### ISSUE TITLE
Bump.

### ISSUE THREAD

**Issue by jdalton** [ua-parser/uap-core#81]
The last bump was in Nov 2014. It's time :D

**Comment by russellwhitaker** [comment]
Usually, if you're going to bump, you bump on an existing issue to do thread necromancy. Not sure what _opening_ with a bump is intended to accomplish though...

**Comment by jdalton** [comment]
> Not sure what opening with a bump is intended to accomplish though

My hope is it's used to spur whatever process is in place to bump.

**Comment by russellwhitaker** [comment]
You're essentially just playing around then, yes?

**Comment by elsigh** [comment]
We have no process that I'm aware of fwiw - if you want to submit a PR I'm sure it can be merged.

**Comment by jdalton** [comment]
@elsigh Cool cool.

**Comment by russellwhitaker** [comment]
Ah, _that's_ what @jdalton was trying to do. Yeah, generally we open an issue with a description of an issue, and a notice that we're about to open / have already opened an associated pull request.
