### ISSUE TITLE
Several recently introduced/modified HTC-related regexes reference non-existent capture groups

### ISSUE THREAD

**Issue by russellwhitaker** [ua-parser/uap-core#85]
I've submitted a PR with fixes which addresses this issue: https://github.com/ua-parser/uap-core/pull/84

**Comment by russellwhitaker** [comment]
@commenthol @mrjgreen I added explanatory context in the associated PR.

**Comment by commenthol** [comment]
PR #84 merged - Thanks

**Comment by russellwhitaker** [comment]
My pleasure @commenthol - thanks for merging.
