### ISSUE TITLE
qutebrowser parsed as Safari 0.0.0

### ISSUE THREAD

**Issue by Sebmaster** [ua-parser/uap-core#96]
[qutebrowser](https://github.com/The-Compiler/qutebrowser) sends a user agent like `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) qutebrowser/0.2.1 Safari/538.1`, which is parsed as Safari 0.0.0.

**Comment by The-Compiler** [comment]
FWIW that's the default QtWebKit useragent (apart from the qutebrowser/... part), so this is likely to affect other QtWebKit browsers (Otter Browser, QupZilla, Rekonq, etc.) as well.

**Comment by commenthol** [comment]
Otter shows up as:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) Otter/0.9.04`
QupZilla as:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.7.0 Safari/538.1`
Reconq is already being detected by `uap-core`

For support of Otter and QupZilla we should open a new issue.
