### ISSUE TITLE
Differentiating from embedded Mobile Safari and real Mobile Safari

### ISSUE THREAD

**Issue by J-Griffin** [ua-parser/uap-core#98]
It appears that the Mobile Safari browser is not differentiated from the embedded "uiwebview" version of the browser. It is useful to know which webkit is rendering the page as the uiwebview version is known for being much worse than the actual Mobile Safari browser.

This is related to #38 but for the iOS side of things. There was also an [issue created in the old UAParser repository](https://github.com/tobie/ua-parser/issues/451), but it was never resolved.

Here is a [SO answer](http://stackoverflow.com/a/5916330) talking about the issue as it applies to iOS.

**Comment by commenthol** [comment]
@J-Griffin can you take a look at https://github.com/ua-parser/uap-core/issues/101 if that matches the required? Thanks.

**Comment by J-Griffin** [comment]
I ran this against our tests which now include UIWebView cases. They passed with this change.
